# Generated by Django 2.1 on 2021-04-02 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyFeedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfeedback_tb',
            name='Userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmodels.User_TB'),
        ),
    ]
