# Generated by Django 2.1 on 2021-04-02 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('post', '0001_initial'),
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='PostId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='Post Id'),
        ),
        migrations.AddField(
            model_name='bid',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company_TB'),
        ),
    ]
