# Generated by Django 2.1 on 2021-04-02 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0003_bid_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='company_name',
        ),
        migrations.AlterField(
            model_name='bid',
            name='PostId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='Post Id'),
        ),
    ]
