# Generated by Django 2.1 on 2021-04-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints_TB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_text', models.CharField(max_length=250, verbose_name='Complaint Text:')),
                ('complaint_date', models.DateTimeField(auto_now_add=True, verbose_name='Complaint Date:')),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User Complaint',
            },
        ),
    ]
