# Generated by Django 2.1 on 2021-04-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=150, verbose_name='Blog Name:')),
                ('blog_title', models.CharField(max_length=150, verbose_name='Blog Title:')),
                ('blog_pics', models.ImageField(upload_to='blogimages/')),
                ('blog_desc', models.TextField(verbose_name='Blog Description:')),
                ('blog_date', models.DateTimeField(auto_now_add=True, verbose_name='Blog Date:')),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog',
            },
        ),
    ]
