# Generated by Django 2.2.10 on 2021-03-19 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_date', models.DateTimeField(auto_now_add=True, verbose_name='Bidding Date:')),
                ('price', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Bidding Price:')),
                ('max_price', models.TextField(blank=True, default='', verbose_name='Base Price')),
                ('PostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='Post Id')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company_TB')),
            ],
            options={
                'verbose_name': 'Bidding',
            },
        ),
    ]
