# Generated by Django 2.1 on 2021-04-02 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=20, verbose_name='Area Name:')),
                ('pincode', models.IntegerField(verbose_name='Pincode:')),
                ('insert_date', models.DateTimeField(auto_now=True, verbose_name='Insert Date:')),
                ('isActive', models.BooleanField(default='True')),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20, verbose_name='City Name:')),
                ('insert_date', models.DateTimeField(auto_now_add=True, verbose_name='Insert Date:')),
                ('isActive', models.BooleanField(default='True')),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=20, verbose_name='State Name:')),
                ('insert_date', models.DateTimeField(auto_now_add=True, verbose_name='Insert Date:')),
                ('isActive', models.BooleanField(default='True')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.state'),
        ),
        migrations.AddField(
            model_name='area',
            name='city_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.city'),
        ),
    ]
