# Generated by Django 2.1 on 2021-04-02 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img', models.FileField(upload_to='postimages/', verbose_name='Post Image:')),
                ('post_desc', models.TextField(max_length=500, verbose_name='Post Description:')),
                ('post_price', models.IntegerField(verbose_name='Estimated Price: ')),
                ('scrap_kg', models.IntegerField(verbose_name='Estimated Scrap in Kg:')),
                ('isActive', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
