# Generated by Django 2.1 on 2021-04-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0002_auto_20210403_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_table',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='company_table',
            name='company_emailid',
        ),
        migrations.RemoveField(
            model_name='company_table',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='company_table',
            name='company_phone',
        ),
    ]
