# Generated by Django 2.1 on 2021-04-02 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valet_Details_TB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valet_fname', models.CharField(max_length=20)),
                ('valet_lname', models.CharField(max_length=20)),
                ('valet_desc', models.CharField(max_length=1000)),
                ('phone', models.IntegerField()),
                ('profile_pic', models.ImageField(blank=True, default='', upload_to='valetprofilepicimages/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company_TB')),
            ],
            options={
                'verbose_name': 'Valet',
            },
        ),
    ]
